prompt("이름")
prompt("오늘 한 운동 종류")
prompt("운동시간(분)")

let 이름 = ("유환빈")
console.log(이름)
let 오늘한운동종류 = ("러닝")
console.log(오늘한운동종류)
let 운동시간 = ("60분")
console.log(운동시간)
let 분당소모칼로리 = ("7kacl")
console.log(분당소모칼로리)
let 총소모칼로리 =("60*7=420")
console.log(총소모칼로리)